### ISSUE TITLE
graphical ticker is no longer changing

### ISSUE THREAD

**Issue by jpittis** [Queens-Hacks/ants#13]

**Comment by MaxBittker** [comment]
now reset is broken :(

**Comment by jpittis** [comment]
Sorry man. I'll get it fixed. :/

**Comment by MaxBittker** [comment]
it's a weird problem, control.js has
 var World = require('./world'); at the top, then when it calls new World.World();, World is an empty object thing or something with no methods

**Comment by jpittis** [comment]
fixed pause on restart with e6872e2f7547751b34552df453cb1e92d651e8ce
fixed restart bug with 771de10dd69ceea458b03c56dc672102702d17f1
fixed ticker with 53132e69dac893c9350faa5cb05592cdf3285c2c, 54c23072e7c8a0fe4e4e21509e3cf0eefad7d0f2 and abd9b799fc4f15490ede706b3b60ad9bad2a296a
