### ISSUE TITLE
Refresh Button Confusion

### ISSUE THREAD

**Issue by MaxBittker** [Queens-Hacks/ants#2]
Currently, some poeple users are assuming that the play button always loads the new from the editor. the UI should make this process more obvious, possible through more explicit instructions, or through an indicator when the code in the editor has been modified since the last refresh. I will probably take care of this when i have time but feel free to beat me to it

**Comment by jpittis** [comment]
Play also has strange behaviour when the game is over. If you press play while on the win screen, the ants start marching again. Maybe fix that bug and make play the same button as pause? have them toggle the icon showing?

**Comment by epilk** [comment]
I think what we really need to do is make it clear to users that the text is in a buffer. Maybe we could make an explicit upload button in addition to refresh? If that's too many buttons we can merge pause and play together since their use is mutually exclusive.

**Comment by mystor** [comment]
How about marking the text editor as read-only while running. We then have one play/pause button, and a reset button. If you change the text in the textbox, the play button will be disabled (grey it out?). That way the code running the game always matches the code in the box?

**Comment by MaxBittker** [comment]
play and pause as the same button is a good idea. I think a fitting a small explanatory warning like "press refresh to run your new code" somewhere that's visible whenever old code is running would prevent user confusion, without limiting people from making changes while they watch their old iteration

**Comment by jpittis** [comment]
Fixed by 516e76c58254222af9dd2eecfcdfd74200a6bff9
