### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by jpittis** [Queens-Hacks/ants#4]
we need a license. talk about it as a group.

**Comment by epilk** [comment]
Lets start off with MIT? (basically we can't be sued, and anyone can do anything with it. (including making a propertiary/not MIT licensed fork))

**Comment by jpittis** [comment]
I'd be down with MIT

**Comment by mystor** [comment]
I'm fine with MIT if everyone is comfortable with not having the project
copylefted.

**Comment by jpittis** [comment]
Fixed by ae09ec5b23abb1485e5f601ec8fb961e399c5937
